// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtpSwFxaJXGVXVI6kWYEQgbkL6YX9OglM',
    appId: '1:191070232753:web:26c2c81eaa785aa0010290',
    messagingSenderId: '191070232753',
    projectId: 'cnc-api-explorer-3fb4e',
    authDomain: 'cnc-api-explorer-3fb4e.firebaseapp.com',
    storageBucket: 'cnc-api-explorer-3fb4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz4RbMNebWtkjo6lGMOp4HOQ98BwuOORk',
    appId: '1:191070232753:android:698dd357684e39f7010290',
    messagingSenderId: '191070232753',
    projectId: 'cnc-api-explorer-3fb4e',
    storageBucket: 'cnc-api-explorer-3fb4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYqACy0maxNiUQ6ABf3jibLcxdlEnNDRE',
    appId: '1:191070232753:ios:e8650893a58ea4e0010290',
    messagingSenderId: '191070232753',
    projectId: 'cnc-api-explorer-3fb4e',
    storageBucket: 'cnc-api-explorer-3fb4e.appspot.com',
    iosClientId: '191070232753-ff5vmqav4i14nku8l751c8ia85ln5u6q.apps.googleusercontent.com',
    iosBundleId: 'com.steveblythe.cncApiExplorer',
  );
}
